setwd("/home/g0017139/UMCG_Thesis/Working_Code/")
#install.packages("MASS",  "/data/g0017139/.envs/r_env/lib/R/library/", repos = "http://cran.us.r-project.org")
# install.packages("HDclassif", repos = "http://cran.us.r-project.org")
# getwd() 

library(HDclassif)
mydata = read.csv("/data/g0017139/gene_expression_norm.dat", sep = ' ', header = FALSE, )
#mydata = read.csv("/data/g0017139/GPL570_norm.dat", sep = ' ', header = FALSE, )

prms <- hddc(mydata, K = 2:3, model = 10, itermax = 400, threshold =  0.01)
print(prms$all_results)
print(prms$class)
#png(filename="Results/Set1/HDDCplot.png")
#plot(prms, "Cattell", 0.01)
#dev.off()
#print(prms$d)
#print(prms$a)
#print(prms$b)
#print(prms$prop)
#df <- do.call("rbind", lapply(prms$class, as.data.frame)) 
#write.csv(df, file = "Results/Set1/ClustersHDDC2.csv")

