#!/bin/bash
#SBATCH --time=100:00:00
#SBATCH --job-name=dbscan2
#SBATCH --output=dbscanSet2.out
#SBATCH --mem=124GB
#SBATCH --ntasks=24
#SBATCH --nodes=1
#SBATCH --partition=regular

module load Anaconda3/2020.11
eval "$(conda shell.bash hook)"
conda activate /data/g0017139/.envs/ClusterEnv

python3 /home/g0017139/UMCG_Thesis/Working_Code/Gridsearch/Main.py -f /data/g0017139/GPL570_norm.dat -a dbscan -s TSet2
