#!/bin/bash
#SBATCH --time=12:00:00
#SBATCH --job-name=dbscan1
#SBATCH --output=dbscanSet1.out
#SBATCH --mem=124GB
#SBATCH --ntasks=2
#SBATCH --nodes=1
#SBATCH --partition=vulture

module load Anaconda3/2020.11
eval "$(conda shell.bash hook)"
conda activate /data/g0017139/.envs/ClusterEnv

python3 /home/g0017139/UMCG_Thesis/Working_Code/Gridsearch/Main.py -f /data/g0017139/gene_expression_norm.dat -a dbscan -s TSet1
